<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 14 Introduction to Linear Models | 5023Y</title>
<meta name="author" content="Philip T. Leftwich">
<meta name="description" content="In the last chapter we conducted a simple analysis of Darwin's maize data using R. We worked out confidence intervals 'by hand'. This simple method allowed us to learn more about analysis,...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 14 Introduction to Linear Models | 5023Y">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ueabio.github.io/data-sci/introduction-to-linear-models.html">
<meta property="og:image" content="https://ueabio.github.io/data-sci/images/logos/twitter_card.png">
<meta property="og:description" content="In the last chapter we conducted a simple analysis of Darwin's maize data using R. We worked out confidence intervals 'by hand'. This simple method allowed us to learn more about analysis,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 14 Introduction to Linear Models | 5023Y">
<meta name="twitter:description" content="In the last chapter we conducted a simple analysis of Darwin's maize data using R. We worked out confidence intervals 'by hand'. This simple method allowed us to learn more about analysis,...">
<meta name="twitter:image" content="https://ueabio.github.io/data-sci/images/logos/twitter_card.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.13/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1.9000/transition.js"></script><script src="libs/bs3compat-0.3.1.9000/tabs.js"></script><script src="libs/bs3compat-0.3.1.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/font-awesome-5.13.0/js/script.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script language="javascript"> 
        function toggle(id) {
            var ele = document.getElementById("toggleText" + id);
            var text = document.getElementById("displayText" + id);
            var buttonText = text.innerHTML.replace("Show ", "");
            buttonText = buttonText.replace("Hide ", "");
            if(ele.style.display == "block") {
                ele.style.display = "none";
                text.innerHTML = "Show " + buttonText;
            } else {
                ele.style.display = "block";
                text.innerHTML = "Hide " + buttonText;
            }
        } 
    </script><script language="javascript">
        function openCode(evt, codeName, id) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent" + id);
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks" + id);
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(codeName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script><script language="javascript">
        function hide(id){
            document.getElementById(id).style.display = "none";
        }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Data Science for Biologists">5023Y</a>:
        <small class="text-muted">Data Science for Biologists</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li class="book-part">R Programming</li>
<li><a class="" href="introduction-to-r-and-rstudio.html"><span class="header-section-number">1</span> Introduction to R and RStudio</a></li>
<li><a class="" href="basic-programming.html"><span class="header-section-number">2</span> Basic programming</a></li>
<li class="book-part">Exploring Data</li>
<li><a class="" href="loading-data.html"><span class="header-section-number">3</span> Loading data</a></li>
<li><a class="" href="data-wrangling-part-one.html"><span class="header-section-number">4</span> Data wrangling part one</a></li>
<li><a class="" href="data-wrangling-part-two.html"><span class="header-section-number">5</span> Data wrangling part two</a></li>
<li><a class="" href="data-visualisation-with-ggplot2.html"><span class="header-section-number">6</span> Data visualisation with ggplot2</a></li>
<li class="book-part">Literate Programming and Reproducibility</li>
<li><a class="" href="markdown.html"><span class="header-section-number">7</span> Markdown</a></li>
<li><a class="" href="github.html"><span class="header-section-number">8</span> Github</a></li>
<li class="book-part">DRY code</li>
<li><a class="" href="functions-1.html"><span class="header-section-number">9</span> Functions</a></li>
<li><a class="" href="iteration.html"><span class="header-section-number">10</span> Iteration</a></li>
<li class="book-part">Advanced Data Insights</li>
<li><a class="" href="data-insights-part-one.html"><span class="header-section-number">11</span> Data Insights part one</a></li>
<li><a class="" href="data-insights-part-two.html"><span class="header-section-number">12</span> Data insights part two</a></li>
<li class="book-part">Statistics</li>
<li><a class="" href="introduction-to-statistics.html"><span class="header-section-number">13</span> Introduction to statistics</a></li>
<li><a class="active" href="introduction-to-linear-models.html"><span class="header-section-number">14</span> Introduction to Linear Models</a></li>
<li><a class="" href="testing.html"><span class="header-section-number">15</span> Testing</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">16</span> Regression</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">17</span> ANOVA</a></li>
<li><a class="" href="multivariate-linear-models.html"><span class="header-section-number">18</span> Multivariate linear models</a></li>
<li><a class="" href="complex-models.html"><span class="header-section-number">19</span> Complex models</a></li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">20</span> Generalized Linear Models</a></li>
<li class="book-part">Advanced topics</li>
<li><a class="" href="mixed-models.html"><span class="header-section-number">21</span> Mixed models</a></li>
<li><a class="" href="generalised-additive-models.html"><span class="header-section-number">22</span> Generalised Additive Models</a></li>
<li><a class="" href="survival-models.html"><span class="header-section-number">23</span> Survival models</a></li>
<li><a class="" href="unsupervised-machine-learning.html"><span class="header-section-number">24</span> Unsupervised Machine Learning</a></li>
<li><a class="" href="power-analysis.html"><span class="header-section-number">25</span> Power analysis</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="updating-r-rstudio-and-packages.html"><span class="header-section-number">B</span> Updating R, RStudio, and packages</a></li>
<li><a class="" href="exporting-files-from-the-server.html"><span class="header-section-number">C</span> Exporting files from the server</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">D</span> Symbols</a></li>
<li><a class="" href="baser.html"><span class="header-section-number">E</span> Base R vs. Tidyverse</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/UEABIO/data-sci-v1">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="introduction-to-linear-models" class="section level1" number="14">
<h1>
<span class="header-section-number">14</span> Introduction to Linear Models<a class="anchor" aria-label="anchor" href="#introduction-to-linear-models"><i class="fas fa-link"></i></a>
</h1>
<p>In the last chapter we conducted a simple analysis of Darwin's maize data using R. We worked out confidence intervals 'by hand'. This simple method allowed us to learn more about analysis, estimates, standard error and confidence. But it is also slow, and it relied on the assumptions of a <em>z-distribution</em> to assess true differences between the groups.</p>
<p>We will now work through a much more efficient way to carry out comparisons, we will use the functions in R that let us perform a <strong>linear model</strong> analysis.</p>
<div id="packages-1" class="section level3" number="14.0.1">
<h3>
<span class="header-section-number">14.0.1</span> Packages<a class="anchor" aria-label="anchor" href="#packages-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb357"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggobi.github.io/ggally/">GGally</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://easystats.github.io/performance/">performance</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="a-linear-model-analysis-for-comparing-groups" class="section level2" number="14.1">
<h2>
<span class="header-section-number">14.1</span> A linear model analysis for comparing groups<a class="anchor" aria-label="anchor" href="#a-linear-model-analysis-for-comparing-groups"><i class="fas fa-link"></i></a>
</h2>
<p>R has a general function <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> for fitting linear models, this is part of base R (does not require the tidyverse packages). We will run through a few different iterations of the linear model increasing in complexity. We will often want to fit several models to our data, so a common way to work is to fit a model and assign it to a named R object, so that we can extract data from when we need it.</p>
<p>In the example below I have called the model <code>lsmodel0</code>, short for "least-squares model 0", this is because the linear-model uses a technique called <strong>least-squares</strong> we will explore what this means later.</p>
<div class="sourceCode" id="cb358"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lsmodel0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span>formula <span class="op">=</span> <span class="va">height</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span></code></pre></div>
<div class="try">
<p>
You can pipe into the lm() function, but when we use functions that are "outside" of the tidyverse family we need to put a <code>.</code> where the data should go (as it is usually not the first argument).
</p>
<p>
lsmodel0 &lt;- darwin %&gt;% lm(height ~ 1, data= .)
</p>
</div>
<p>The first argument of the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function is formula (we won't write this out in full in the future) - and this specifies we want to analyse a <strong>response</strong> variable (height) as a function of an <strong>explanatory</strong> variable using the <em>tilde</em> symbol (~).</p>
<p>The simplest possible model ignores any explanatory variables, instead the <code>1</code> indicates we just want to estimate an intercept. Without explanatory variables this means the formula will just estimate the overall mean height of <strong>all</strong> the plants in the dataset.</p>
</div>
<div id="summaries-for-models" class="section level2" number="14.2">
<h2>
<span class="header-section-number">14.2</span> Summaries for models<a class="anchor" aria-label="anchor" href="#summaries-for-models"><i class="fas fa-link"></i></a>
</h2>
<p>When you have made a linear model, we can investigate a summary of the model using the base R function <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code>. There is also a tidyverse option provided by the package <code>broom</code>(<span class="citation">(<a href="#ref-R-broom" role="doc-biblioref"><strong>R-broom?</strong></a>)</span>).</p>
<div id="broom" class="section level3" number="14.2.1">
<h3>
<span class="header-section-number">14.2.1</span> Broom<a class="anchor" aria-label="anchor" href="#broom"><i class="fas fa-link"></i></a>
</h3>
<p>broom summarizes key information about models in tidy <code>tibble()s</code>. broom provides three verbs to make it convenient to interact with model objects:</p>
<ul>
<li><p><code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> summarizes information about model components</p></li>
<li><p><code><a href="https://generics.r-lib.org/reference/glance.html">broom::glance()</a></code> reports information about the entire model</p></li>
<li><p><code><a href="https://generics.r-lib.org/reference/augment.html">broom::augment()</a></code> adds informations about individual observations to a dataset and it can be used to model predictions onto a new dataset.</p></li>
</ul>
</div>
<div id="model-summary" class="section level3" number="14.2.2">
<h3>
<span class="header-section-number">14.2.2</span> Model summary<a class="anchor" aria-label="anchor" href="#model-summary"><i class="fas fa-link"></i></a>
</h3>
<button id="displayTextunnamed-chunk-6" onclick="javascript:toggle('unnamed-chunk-6');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-6" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="tab">
<button class="tablinksunnamed-chunk-6 active" onclick="javascript:openCode(event, 'option1unnamed-chunk-6', 'unnamed-chunk-6');">
Base R
</button>
<button class="tablinksunnamed-chunk-6" onclick="javascript:openCode(event, 'option2unnamed-chunk-6', 'unnamed-chunk-6');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1unnamed-chunk-6" class="tabcontentunnamed-chunk-6">
<div class="sourceCode" id="cb359"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lsmodel0</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ 1, data = darwin)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.8833 -1.3521 -0.0083  2.4917  4.6167 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  18.8833     0.5808   32.52   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.181 on 29 degrees of freedom</code></pre>
</div>
<div id="option2unnamed-chunk-6" class="tabcontentunnamed-chunk-6">
<div class="sourceCode" id="cb361"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lsmodel0</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
18.88333
</td>
<td style="text-align:right;">
0.5807599
</td>
<td style="text-align:right;">
32.51487
</td>
<td style="text-align:right;">
0
</td>
</tr></tbody>
</table></div>
</div>
</div>
<script> javascript:hide('option2unnamed-chunk-6') </script>
</div>
</div>
</div>
<p>The output above is called the <em>table of coefficients</em>. The 18.9 is the <em>estimate of the model coefficient</em> (in this case it is the overall mean), together with its standard error. The first row in any R model output is always labelled the 'Intercept' and the challenge is usually to workout what that represents. In this case we can prove that this is the same as the overall mean as follows:</p>
<div class="sourceCode" id="cb362"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">$</span><span class="va">height</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 18.88333</code></pre>
<p>This simple model allows us to understand what the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function does.</p>
</div>
<div id="compare-means" class="section level3" number="14.2.3">
<h3>
<span class="header-section-number">14.2.3</span> Compare means<a class="anchor" aria-label="anchor" href="#compare-means"><i class="fas fa-link"></i></a>
</h3>
<p>What we really want is a linear model that analyses the <em>difference</em> in average plant height as a function of pollination type. We can use the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function to fit this as a linear model as follows:</p>
<div class="sourceCode" id="cb364"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lsmodel1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span>, data<span class="op">=</span><span class="va">darwin</span><span class="op">)</span>

<span class="co"># note that the following is identical</span>

<span class="co"># lsmodel1 &lt;- lm(height ~ 1 + type, data=darwin)</span></code></pre></div>
<p>Now the model formula contains the pollination type in addition to an intercept.</p>
<div class="sourceCode" id="cb365"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lsmodel1</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
20.191667
</td>
<td style="text-align:right;">
0.7592028
</td>
<td style="text-align:right;">
26.595880
</td>
<td style="text-align:right;">
0.0000000
</td>
</tr>
<tr>
<td style="text-align:left;">
typeSelf
</td>
<td style="text-align:right;">
-2.616667
</td>
<td style="text-align:right;">
1.0736749
</td>
<td style="text-align:right;">
-2.437113
</td>
<td style="text-align:right;">
0.0214145
</td>
</tr>
</tbody>
</table></div>
</div>
<p>Some things to notice about the above:</p>
<ol style="list-style-type: decimal">
<li><p>The intercept value has changed! So what does it represent now?</p></li>
<li><p>The label of the second row is 'typeSelf'</p></li>
</ol>
<p>But what does this mean? Think about it and see if you can figure it out for yourself before clicking the reveal</p>
<button id="displayTextunnamed-chunk-10" onclick="javascript:toggle('unnamed-chunk-10');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-10" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>The label of the second row 'typeSelf' is produced by combining the variable type, with one of the factors (Self). As there are only two levels in type, it stands to reason that the intercept must represent typeCross. So the coefficient in the label intercept is the average height of the 15 maize plants in the crossed treatment.</p>
<p>So what about the second row? A common mistake is to think that this must refer to the height of the Self plants. However, this cannot be true as the value is <em>negative</em>. Instead what it actually refers to is the <strong>difference in the mean height of the two groups</strong>. This focuses then on the question which we are asking: is their a difference in the height of plants that result from cross pollination when compared to plants that have been self pollinated?</p>
<p>This linear model indicates the average height of Crossed plants is 20.2 inches, and Selfed plants are an average of 2.6 inches <em>shorter</em>.</p>
<p>You can confirm this for yourself:</p>
<div class="sourceCode" id="cb366"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
type
</th>
<th style="text-align:right;">
mean
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Cross
</td>
<td style="text-align:right;">
20.19167
</td>
</tr>
<tr>
<td style="text-align:left;">
Self
</td>
<td style="text-align:right;">
17.57500
</td>
</tr>
</tbody>
</table></div>
</div>
</div>
</div>
</div>
<p>Let's take a look at a fuller summary of our model, to see what else we can determine</p>
<div class="sourceCode" id="cb367"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lsmodel1</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ type, data = darwin)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.1917 -1.0729  0.8042  1.9021  3.3083 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  20.1917     0.7592  26.596   &lt;2e-16 ***
## typeSelf     -2.6167     1.0737  -2.437   0.0214 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.94 on 28 degrees of freedom
## Multiple R-squared:  0.175,  Adjusted R-squared:  0.1455 
## F-statistic:  5.94 on 1 and 28 DF,  p-value: 0.02141</code></pre>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="images/model%20summary.png" alt="Annotation of the summary function output" width="80%"><p class="caption">
Figure 14.1: Annotation of the summary function output
</p>
</div>
<p>We could use the information from this model to superimpose the calculated means onto a plot.</p>
<div class="sourceCode" id="cb369"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">type</span>, 
             y<span class="op">=</span><span class="va">height</span>,
             colour<span class="op">=</span><span class="va">type</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>alpha<span class="op">=</span><span class="fl">0.5</span>,
              width<span class="op">=</span><span class="fl">0.1</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun<span class="op">=</span><span class="va">mean</span>,
               size<span class="op">=</span><span class="fl">1.2</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-13-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
<div id="standard-error-of-the-difference-1" class="section level3" number="14.2.4">
<h3>
<span class="header-section-number">14.2.4</span> Standard error of the difference<a class="anchor" aria-label="anchor" href="#standard-error-of-the-difference-1"><i class="fas fa-link"></i></a>
</h3>
<p>The output of the model also gives the standard errors of the values (estimates). In the first row the intercept calculates a mean and the standard error of the mean (SEM). As the second row gives the mean <em>difference</em> in this column it gives the <em>standard error of the difference</em> between the two means (SED). We have already seen how to calculate SEM, but what about SED?</p>
<p><span class="math display">\[
SED = {\sqrt \frac{s_1^2}{n_1}}+\frac{s_2^2}{n_2}
\]</span></p>
<blockquote>
<p>** Note - The subscripts 1 and 2 indicate the two groups (self and cross).</p>
</blockquote>
<div class="info">
<p>
Our linear model analysis doesn't actually calculate the individual variances for the two groups. Instead it uses a 'pooled' variance approach. This assumes the variance is roughly equal across all groups, and allows us to take advantage of the larger sample size through 'pooling', to generate a more accurate SED. However, this does assume that variance is <em>roughly equal</em> in the two groups. In fact last week when we calculated standard deviation, we saw this was not the case. So we must check this assumption in our model (more on this later).
</p>
</div>
</div>
</div>
<div id="confidence-intervals-1" class="section level2" number="14.3">
<h2>
<span class="header-section-number">14.3</span> Confidence intervals<a class="anchor" aria-label="anchor" href="#confidence-intervals-1"><i class="fas fa-link"></i></a>
</h2>
<button id="displayTextunnamed-chunk-15" onclick="javascript:toggle('unnamed-chunk-15');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-15" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="tab">
<button class="tablinksunnamed-chunk-15 active" onclick="javascript:openCode(event, 'option1unnamed-chunk-15', 'unnamed-chunk-15');">
Base R
</button>
<button class="tablinksunnamed-chunk-15" onclick="javascript:openCode(event, 'option2unnamed-chunk-15', 'unnamed-chunk-15');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1unnamed-chunk-15" class="tabcontentunnamed-chunk-15">
<div class="sourceCode" id="cb370"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/confint.html">confint</a></span><span class="op">(</span><span class="va">lsmodel1</span><span class="op">)</span></code></pre></div>
<pre><code>##                2.5 %     97.5 %
## (Intercept) 18.63651 21.7468231
## typeSelf    -4.81599 -0.4173433</code></pre>
</div>
<div id="option2unnamed-chunk-15" class="tabcontentunnamed-chunk-15">
<div class="sourceCode" id="cb372"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lsmodel1</span>, conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
20.191667
</td>
<td style="text-align:right;">
0.7592028
</td>
<td style="text-align:right;">
26.595880
</td>
<td style="text-align:right;">
0.0000000
</td>
<td style="text-align:right;">
18.63651
</td>
<td style="text-align:right;">
21.7468231
</td>
</tr>
<tr>
<td style="text-align:left;">
typeSelf
</td>
<td style="text-align:right;">
-2.616667
</td>
<td style="text-align:right;">
1.0736749
</td>
<td style="text-align:right;">
-2.437113
</td>
<td style="text-align:right;">
0.0214145
</td>
<td style="text-align:right;">
-4.81599
</td>
<td style="text-align:right;">
-0.4173433
</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<script> javascript:hide('option2unnamed-chunk-15') </script>
</div>
</div>
</div>
<p>Because this follows the same layout as the table of coefficients, the output intercept row gives a 95% CI for the height of the crossed plants and the second row gives a 95% interval for the <em>difference in height between crossed and selfed plants</em>. The lower and upper bounds are the 2.5% and 97.5% of a <em>t</em>-distribution (more on this later).</p>
<p>It is this difference in height in which we are specifically interested. Our summary models have generated <em>p</em>-values but we have conspicuously ignored these for now. Instead we are going to continue to focus on using confidence intervals to answer our question.</p>
</div>
<div id="answering-the-question" class="section level2" number="14.4">
<h2>
<span class="header-section-number">14.4</span> Answering the question<a class="anchor" aria-label="anchor" href="#answering-the-question"><i class="fas fa-link"></i></a>
</h2>
<p>Darwin's original hypothesis was that self-pollination would reduce fitness (using height as a proxy for this). The null hypothesis is that there is no effect of pollination type, and therefore no difference in the average heights.
We must ask ourselves if our experiment is consistent with this null hypothesis or can we reject it? If we choose to reject the null hypothesis, with what level of confidence can we do so?</p>
<p>To do this, we can simply whether or not the predicted value of our null hypothesis (a difference of zero) lies inside the 95% CI for the difference of the mean.</p>
<p>If our confidence intervals contain zero (or no difference), then we cannot establish a difference between our sample difference in height (-2.62 inches) from the null prediction of zero difference, given the level of variability (noise) in our data.</p>
<p>In this case we can see that the upper and lower bounds of the confidence intervals do not cross zero. The difference in height is consistent with Darwin's alternate hypothesis of inbreeding depression.</p>
<p>The <code>GGally</code> package has a handy <code><a href="https://ggobi.github.io/ggally/reference/ggcoef_model.html">ggcoef_model()</a></code> function, that produces a graph of the estimated mean difference with an approx 95% CI. As we can see we are able to reject the null hypothesis at a 95% confidence level.</p>
<div class="sourceCode" id="cb373"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">GGally</span><span class="fu">::</span><span class="fu"><a href="https://ggobi.github.io/ggally/reference/ggcoef_model.html">ggcoef_model</a></span><span class="op">(</span><span class="va">lsmodel1</span>,
                     show_p_values<span class="op">=</span><span class="cn">FALSE</span>, 
                     conf.level<span class="op">=</span><span class="fl">0.95</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-16-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="try">
<p>
Set the confidence levels to 99%, do you think the difference between treatments is still statistically significant at an of 0.01?
</p>
</div>
<p>If we increase the level of confidence (from 95% to 99%, roughly 2 SE to 3 SE), then we may find that we cannot reject the null hypothesis at a higher threshold of confidence. Try altering the conf.level argument above for yourself to see this in action.</p>
<p>We can also include this argument in the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function if we wish to:</p>
<div class="sourceCode" id="cb374"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lsmodel1</span>, conf.int<span class="op">=</span><span class="cn">T</span>, conf.level<span class="op">=</span><span class="fl">0.99</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
20.191667
</td>
<td style="text-align:right;">
0.7592028
</td>
<td style="text-align:right;">
26.595880
</td>
<td style="text-align:right;">
0.0000000
</td>
<td style="text-align:right;">
18.093790
</td>
<td style="text-align:right;">
22.2895433
</td>
</tr>
<tr>
<td style="text-align:left;">
typeSelf
</td>
<td style="text-align:right;">
-2.616667
</td>
<td style="text-align:right;">
1.0736749
</td>
<td style="text-align:right;">
-2.437113
</td>
<td style="text-align:right;">
0.0214145
</td>
<td style="text-align:right;">
-5.583512
</td>
<td style="text-align:right;">
0.3501789
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="getting-the-other-treatment-mean-and-standard-error" class="section level3" number="14.4.1">
<h3>
<span class="header-section-number">14.4.1</span> Getting the other treatment mean and standard error<a class="anchor" aria-label="anchor" href="#getting-the-other-treatment-mean-and-standard-error"><i class="fas fa-link"></i></a>
</h3>
<p>One limitation of the table of coefficients output is that it doesn't provide the mean and standard error of the <em>other</em> treatment level (only the difference between them). If we wish to calculate the "other" mean and SE then we can get R to do this.</p>
<div class="sourceCode" id="cb375"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>type<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>type<span class="op">=</span><span class="fu">fct_relevel</span><span class="op">(</span><span class="va">type</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Self"</span>, <span class="st">"Cross"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span><span class="op">~</span><span class="va">type</span>, data<span class="op">=</span><span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
17.575000
</td>
<td style="text-align:right;">
0.7592028
</td>
<td style="text-align:right;">
23.149282
</td>
<td style="text-align:right;">
0.0000000
</td>
</tr>
<tr>
<td style="text-align:left;">
typeCross
</td>
<td style="text-align:right;">
2.616667
</td>
<td style="text-align:right;">
1.0736749
</td>
<td style="text-align:right;">
2.437113
</td>
<td style="text-align:right;">
0.0214145
</td>
</tr>
</tbody>
</table></div>
</div>
<p>After relevelling, the self treatment is now taken as the intercept, and we get the estimate for it's mean and standard error</p>
</div>
<div id="emmeans" class="section level3" number="14.4.2">
<h3>
<span class="header-section-number">14.4.2</span> Emmeans<a class="anchor" aria-label="anchor" href="#emmeans"><i class="fas fa-link"></i></a>
</h3>
<p>We could also use the package <a href="https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/"><code>emmeans</code></a> and its function <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> to do a similar thing</p>
<div class="sourceCode" id="cb376"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">means</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">lsmodel1</span>, specs <span class="op">=</span> <span class="op">~</span> <span class="va">type</span><span class="op">)</span>

<span class="va">means</span></code></pre></div>
<pre><code>##  type  emmean    SE df lower.CL upper.CL
##  Cross   20.2 0.759 28     18.6     21.7
##  Self    17.6 0.759 28     16.0     19.1
## 
## Confidence level used: 0.95</code></pre>
<p>The advantage of emmeans is that it provides the mean, standard error and 95% confidence interval estimates of all levels from the model at once (e.g. it relevels the model multiple times behind the scenes).</p>
<p><code>emmeans</code> also gives us a handy summary to include in data visuals that combine raw data and statistical inferences. These are standard <code><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot()</a></code> outputs so can be <a href="data-visualisation-with-ggplot2.html#intro-to-grammar">customised as much as you want</a>.</p>
<div class="sourceCode" id="cb378"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">means</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">type</span>, 
             y<span class="op">=</span><span class="va">emmean</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>
    ymin<span class="op">=</span><span class="va">lower.CL</span>, 
    ymax<span class="op">=</span><span class="va">upper.CL</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-21-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>Notice that no matter how we calculate the estimated SE (and therefore the 95% CI) of both treatments is the same. This is because as mentioned earlier the variance is a pooled estimate, e.g. variance is not being calculate separately for each group. The only difference you should see in SE across treatments will be if there is a difference in <em>sample size</em> between groups.</p>
<div class="info">
<p>
Notice how the Confidence intervals of the estimated means strongly overlap, there is a difference between the two SEMs and the SED we have calculated. So overlapping error bars cannot be used to infer significance.
</p>
</div>
<p>Because of this pooled variance, there is an assumption that variance is equal across the groups, this and other assumptions of the linear model should be checked. We cannot trust our results if the assumptions of the model are not adequately met.</p>
</div>
</div>
<div id="assumption-checking" class="section level2" number="14.5">
<h2>
<span class="header-section-number">14.5</span> Assumption checking<a class="anchor" aria-label="anchor" href="#assumption-checking"><i class="fas fa-link"></i></a>
</h2>
<p>So now we have been through the main parts of a linear model analysis, we have results and inferences. But we need to check whether the assumptions of the model are adequately met so that we know whether our analysis can be trusted.</p>
<p>In this first part we are going to check two of our assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>that the residual/unexplained variance in our data is approximately <em>normally distributed</em>.</p></li>
<li><p>that the residual/unexplained variance is approximately <em>equal</em> between our groups</p></li>
</ol>
<p>Residuals are the differences between the observed values and the fitted values produced by the model - in this case the heights of the plants against the treatment means. The assumption of a normal distribution applies because the linear model uses this to calculate the standard errors (and therefore confidence intervals). The assumption of equal variance applies because of this pooled variance approach (e.g. we have two treatments with 15 replicates - but by pooling the variance across treatments we have a sample size of 30).</p>
<p>Several functions exist to check assumptions of linear models, and the easiest way to do this is to make graphs. We can do this in several ways, in base R with the <code><a href="https://rdrr.io/r/graphics/plot.html">plot()</a></code> function, and by using the <code><a href="https://easystats.github.io/performance/reference/check_model.html">performance::check_model()</a></code> function.</p>
<button id="displayTextunnamed-chunk-23" onclick="javascript:toggle('unnamed-chunk-23');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-23" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="tab">
<button class="tablinksunnamed-chunk-23 active" onclick="javascript:openCode(event, 'option1unnamed-chunk-23', 'unnamed-chunk-23');">
Base R
</button>
<button class="tablinksunnamed-chunk-23" onclick="javascript:openCode(event, 'option2unnamed-chunk-23', 'unnamed-chunk-23');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1unnamed-chunk-23" class="tabcontentunnamed-chunk-23">
<div class="sourceCode" id="cb379"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">lsmodel1</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-38-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
<div id="option2unnamed-chunk-23" class="tabcontentunnamed-chunk-23">
<div class="sourceCode" id="cb380"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span><span class="op">(</span><span class="va">lsmodel1</span><span class="op">)</span></code></pre></div>
<p><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-39-1.png" width="100%" style="display: block; margin: auto;"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-39-2.png" width="100%" style="display: block; margin: auto;"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-39-3.png" width="100%" style="display: block; margin: auto;"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-39-4.png" width="100%" style="display: block; margin: auto;"></p>
</div>
<script> javascript:hide('option2unnamed-chunk-23') </script>
</div>
</div>
</div>
<div id="normal-distribution-2" class="section level3" number="14.5.1">
<h3>
<span class="header-section-number">14.5.1</span> Normal distribution<a class="anchor" aria-label="anchor" href="#normal-distribution-2"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb381"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">lsmodel1</span>, check<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"normality"</span>,<span class="st">"qq"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-24-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb382"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span><span class="op">(</span><span class="va">lsmodel1</span>, which<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-25-1.png" width="100%" style="display: block; margin: auto;"></div>
<div id="what-is-a-quantile-quantile-qq-plot" class="section level4" number="14.5.1.1">
<h4>
<span class="header-section-number">14.5.1.1</span> What is a Quantile-Quantile (QQ) plot?<a class="anchor" aria-label="anchor" href="#what-is-a-quantile-quantile-qq-plot"><i class="fas fa-link"></i></a>
</h4>
<p>A QQ plot is a classic way of checking whether a sample distribution is the same as another (or theoretical distribution). They look a bit odd at first, but they are actually fairly easy to understand, and very useful! The qqplot distributes your data on the y-axis, and a theoretical normal distribution on the x-axis. If the residuals follow a normal distribution, they should meet to produce a perfect diagonal line across the plot.</p>
<p>Watch this video to see <a href="https://www.youtube.com/watch?v=okjYjClSjOg">QQ plots explained</a></p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-26"></span>
<img src="images/qq_example.png" alt="Examples of qqplots with different deviations from a normal distribution" width="80%"><p class="caption">
Figure 14.2: Examples of qqplots with different deviations from a normal distribution
</p>
</div>
<p>In our example we can see that <em>most</em> of our residuals can be explained by a normal distribution, except at the extreme low end of our data. This is not surprising, as we already identified some potential outliers.</p>
<p>So the fit is not perfect, but it is also not terrible!</p>
</div>
</div>
<div id="equal-variance" class="section level3" number="14.5.2">
<h3>
<span class="header-section-number">14.5.2</span> Equal variance<a class="anchor" aria-label="anchor" href="#equal-variance"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">lsmodel1</span>, check<span class="op">=</span><span class="st">"homogeneity"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-27-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb384"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span><span class="op">(</span><span class="va">lsmodel1</span>, which<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-28-1.png" width="100%" style="display: block; margin: auto;"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-28-2.png" width="100%" style="display: block; margin: auto;"></p>
<p>In order to assess if variances are equal we can plot the residuals (variance) of our data against the fitted (predicted) values. If the residuals were zero, this would mean there is no error, and our data exactly matches our estimates. In reality, there will always be residual error, but as long as it is evenly distributed between treatments this is ok.</p>
<p>The <code>check_models</code> plot provides what we call 'standardized residuals' where we divide the residual error by the standard deviation.</p>
<p>In this instance we can see that the higher fitted values (Cross treatment) appears to be more variable than the lower fitted values. Again, this is not too bad, but not perfect. This is probably being influence at least partially by the potential outliers.</p>
</div>
<div id="outliers" class="section level3" number="14.5.3">
<h3>
<span class="header-section-number">14.5.3</span> Outliers<a class="anchor" aria-label="anchor" href="#outliers"><i class="fas fa-link"></i></a>
</h3>
<p>We have talked a lot about the potential effect of outliers, we can see that they are potentially affecting our estimates of error/variance. However, we should also check how much of an effect they might be having on the model estimates (means). This is where formal outlier tests are useful.</p>
<div class="sourceCode" id="cb385"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">performance</span><span class="fu">::</span><span class="fu"><a href="https://easystats.github.io/performance/reference/check_model.html">check_model</a></span><span class="op">(</span><span class="va">lsmodel1</span>, check<span class="op">=</span><span class="st">"outliers"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-29-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb386"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span><span class="op">(</span><span class="va">lsmodel1</span>, which<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>,<span class="fl">4</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-30-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>The value which the data points are being measured against is called Cook's distance. This is a measure of how much 'leverage' a single data point is exerting on the model, if it is too high, it may be having an outsized effect on the estimates. The <code><a href="https://easystats.github.io/performance/reference/check_model.html">check_model()</a></code> function gives contours to indicate whether data points fall inside or outside the margins for affecting fit, but a rough estimate for an acceptable Cook's Distance is either <span class="math inline">\(\frac{4}{N}\)</span> or <span class="math inline">\(\frac{4}{df}\)</span>, but you are unlikely to have to calculate this by hand.</p>
</div>
</div>
<div id="summary-3" class="section level2" number="14.6">
<h2>
<span class="header-section-number">14.6</span> Summary<a class="anchor" aria-label="anchor" href="#summary-3"><i class="fas fa-link"></i></a>
</h2>
<p>So what can we determine from this analysis? Our model is not perfect, however it is reasonably good. However, we have not addressed an important part of our experimental design yet. The fact that the plants are paired, so in this example we have basically carried out a Student's t-test, not a paired t-test. Later we will add pair as another explanatory variable and see how this affects our model.</p>
<p>So remember a linear model sets one factor level as the 'intercept' estimates its mean, then draws a line from the first treatment to the second treatment, the slope of the line is the difference in means between the two treatments.</p>
<p>The difference in means is always accompanied by a standard error of the difference (SED), and this can be used to calculate a 95% confidence interval. If this confidence interval does not contain the intercept value, we can reject the null hypothesis that there is 'no effect'.</p>
<p>Linear models make a variety of assumptions, including that the noise (residual differences) are approximately normally distributed, with roughly equal (homogenous) variance.</p>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">type</span>, 
             y<span class="op">=</span><span class="va">height</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
   <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width<span class="op">=</span><span class="fl">0.1</span>, 
              pch<span class="op">=</span><span class="fl">21</span>, 
              <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill<span class="op">=</span><span class="va">type</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_segment</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="fl">1</span>, xend<span class="op">=</span><span class="fl">2</span>, y<span class="op">=</span><span class="fl">20.192</span>, yend<span class="op">=</span><span class="fl">20.192</span><span class="op">-</span><span class="fl">2.617</span><span class="op">)</span>, linetype<span class="op">=</span><span class="st">"dashed"</span><span class="op">)</span><span class="op">+</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun.y<span class="op">=</span><span class="va">mean</span>, geom<span class="op">=</span><span class="st">"crossbar"</span>, width<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="13-Introduction-to-linear-models_files/figure-html/unnamed-chunk-31-1.png" width="100%" style="display: block; margin: auto;"></div>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    license
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="introduction-to-statistics.html"><span class="header-section-number">13</span> Introduction to statistics</a></div>
<div class="next"><a href="testing.html"><span class="header-section-number">15</span> Testing</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#introduction-to-linear-models"><span class="header-section-number">14</span> Introduction to Linear Models</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#packages-1"><span class="header-section-number">14.0.1</span> Packages</a></li></ul>
</li>
<li><a class="nav-link" href="#a-linear-model-analysis-for-comparing-groups"><span class="header-section-number">14.1</span> A linear model analysis for comparing groups</a></li>
<li>
<a class="nav-link" href="#summaries-for-models"><span class="header-section-number">14.2</span> Summaries for models</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#broom"><span class="header-section-number">14.2.1</span> Broom</a></li>
<li><a class="nav-link" href="#model-summary"><span class="header-section-number">14.2.2</span> Model summary</a></li>
<li><a class="nav-link" href="#compare-means"><span class="header-section-number">14.2.3</span> Compare means</a></li>
<li><a class="nav-link" href="#standard-error-of-the-difference-1"><span class="header-section-number">14.2.4</span> Standard error of the difference</a></li>
</ul>
</li>
<li><a class="nav-link" href="#confidence-intervals-1"><span class="header-section-number">14.3</span> Confidence intervals</a></li>
<li>
<a class="nav-link" href="#answering-the-question"><span class="header-section-number">14.4</span> Answering the question</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#getting-the-other-treatment-mean-and-standard-error"><span class="header-section-number">14.4.1</span> Getting the other treatment mean and standard error</a></li>
<li><a class="nav-link" href="#emmeans"><span class="header-section-number">14.4.2</span> Emmeans</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#assumption-checking"><span class="header-section-number">14.5</span> Assumption checking</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#normal-distribution-2"><span class="header-section-number">14.5.1</span> Normal distribution</a></li>
<li><a class="nav-link" href="#equal-variance"><span class="header-section-number">14.5.2</span> Equal variance</a></li>
<li><a class="nav-link" href="#outliers"><span class="header-section-number">14.5.3</span> Outliers</a></li>
</ul>
</li>
<li><a class="nav-link" href="#summary-3"><span class="header-section-number">14.6</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/UEABIO/data-sci-v1/blob/main/book/13-Introduction-to-linear-models.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/UEABIO/data-sci-v1/edit/main/book/13-Introduction-to-linear-models.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>5023Y</strong>: Data Science for Biologists" was written by Philip T. Leftwich. It was last built on 2022-09-26.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
