<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 12 Introduction to statistics | 5023Y</title>
<meta name="author" content="Philip T. Leftwich">
<meta name="description" content="This term we will be focusing more on statistics. We actually did quite a lot of descriptive statistics work last term. Every time we summarised or described our data, by calculating a mean,...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 12 Introduction to statistics | 5023Y">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ueabio.github.io/data-sci/introduction-to-statistics.html">
<meta property="og:image" content="https://ueabio.github.io/data-sci/images/logos/twitter_card.png">
<meta property="og:description" content="This term we will be focusing more on statistics. We actually did quite a lot of descriptive statistics work last term. Every time we summarised or described our data, by calculating a mean,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 12 Introduction to statistics | 5023Y">
<meta name="twitter:description" content="This term we will be focusing more on statistics. We actually did quite a lot of descriptive statistics work last term. Every time we summarised or described our data, by calculating a mean,...">
<meta name="twitter:image" content="https://ueabio.github.io/data-sci/images/logos/twitter_card.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.13/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1.9000/transition.js"></script><script src="libs/bs3compat-0.3.1.9000/tabs.js"></script><script src="libs/bs3compat-0.3.1.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/font-awesome-5.13.0/js/script.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script language="javascript"> 
        function toggle(id) {
            var ele = document.getElementById("toggleText" + id);
            var text = document.getElementById("displayText" + id);
            var buttonText = text.innerHTML.replace("Show ", "");
            buttonText = buttonText.replace("Hide ", "");
            if(ele.style.display == "block") {
                ele.style.display = "none";
                text.innerHTML = "Show " + buttonText;
            } else {
                ele.style.display = "block";
                text.innerHTML = "Hide " + buttonText;
            }
        } 
    </script><script language="javascript">
        function openCode(evt, codeName, id) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent" + id);
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks" + id);
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(codeName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script><script language="javascript">
        function hide(id){
            document.getElementById(id).style.display = "none";
        }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Data Science for Biologists">5023Y</a>:
        <small class="text-muted">Data Science for Biologists</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li class="book-part">Get Started in R</li>
<li><a class="" href="introduction-to-r-and-rstudio.html"><span class="header-section-number">1</span> Introduction to R and RStudio</a></li>
<li><a class="" href="r-basics.html"><span class="header-section-number">2</span> R Basics</a></li>
<li class="book-part">Exploring Data</li>
<li><a class="" href="loading-data.html"><span class="header-section-number">3</span> Loading data</a></li>
<li><a class="" href="data-wrangling-part-one.html"><span class="header-section-number">4</span> Data wrangling part one</a></li>
<li><a class="" href="data-wrangling-part-two.html"><span class="header-section-number">5</span> Data wrangling part two</a></li>
<li><a class="" href="data-visualisation-with-ggplot2.html"><span class="header-section-number">6</span> Data visualisation with ggplot2</a></li>
<li class="book-part">Literate Programming and Reproducibility</li>
<li><a class="" href="markdown.html"><span class="header-section-number">7</span> Markdown</a></li>
<li><a class="" href="github.html"><span class="header-section-number">8</span> Github</a></li>
<li class="book-part">R Programming</li>
<li><a class="" href="functions-1.html"><span class="header-section-number">9</span> Functions</a></li>
<li class="book-part">Advanced Data Insights</li>
<li><a class="" href="data-insights-part-one.html"><span class="header-section-number">10</span> Data Insights part one</a></li>
<li><a class="" href="data-insights-part-two.html"><span class="header-section-number">11</span> Data insights part two</a></li>
<li class="book-part">Statistics</li>
<li><a class="active" href="introduction-to-statistics.html"><span class="header-section-number">12</span> Introduction to statistics</a></li>
<li><a class="" href="introduction-to-linear-models.html"><span class="header-section-number">13</span> Introduction to Linear Models</a></li>
<li><a class="" href="testing.html"><span class="header-section-number">14</span> Testing</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">15</span> Regression</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">16</span> ANOVA</a></li>
<li><a class="" href="multivariate-linear-models.html"><span class="header-section-number">17</span> Multivariate linear models</a></li>
<li><a class="" href="complex-models.html"><span class="header-section-number">18</span> Complex models</a></li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">19</span> Generalized Linear Models</a></li>
<li class="book-part">Advanced topics</li>
<li><a class="" href="mixed-models.html"><span class="header-section-number">20</span> Mixed models</a></li>
<li><a class="" href="generalised-additive-models.html"><span class="header-section-number">21</span> Generalised Additive Models</a></li>
<li><a class="" href="survival-models.html"><span class="header-section-number">22</span> Survival models</a></li>
<li><a class="" href="unsupervised-machine-learning.html"><span class="header-section-number">23</span> Unsupervised Machine Learning</a></li>
<li><a class="" href="power-analysis.html"><span class="header-section-number">24</span> Power analysis</a></li>
<li><a class="" href="iteration.html"><span class="header-section-number">25</span> Iteration</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="updating-r-rstudio-and-packages.html"><span class="header-section-number">B</span> Updating R, RStudio, and packages</a></li>
<li><a class="" href="exporting-files-from-the-server.html"><span class="header-section-number">C</span> Exporting files from the server</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">D</span> Symbols</a></li>
<li><a class="" href="baser.html"><span class="header-section-number">E</span> Base R vs. Tidyverse</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/UEABIO/data-sci-v1">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="introduction-to-statistics" class="section level1" number="12">
<h1>
<span class="header-section-number">12</span> Introduction to statistics<a class="anchor" aria-label="anchor" href="#introduction-to-statistics"><i class="fas fa-link"></i></a>
</h1>
<p>This term we will be focusing more on <em>statistics</em>. We actually did quite a lot of <em>descriptive statistics</em> work last term. Every time we summarised or described our data, by calculating a <strong>mean</strong>, <strong>median</strong>, <strong>standard deviation</strong>, <strong>frequency/count</strong>, or <strong>distribution</strong> we were carrying out <em>descriptive statistics</em> that helped us understand our data better.</p>
<p>We are building on this to develop our skills in <em>inferential statistics</em>. Inferential statistics allow us to make generalisations - taking a descriptive statistics from our data such as the <strong>sample mean</strong>, and using it to say something about a population parameter (i.e. the <strong>population mean</strong>).</p>
<p>For example we might measure the measure the heights of some plants that have been outcrossed and inbred and make some summaries and figures to construct an average difference in height (this is <strong>descriptive</strong>). Or we could use this to produce some estimates of the general effect of outcrossing vs inbreeding on plant heights (this is <strong>inferential</strong>).</p>
<div id="darwins-maize-data" class="section level2" number="12.1">
<h2>
<span class="header-section-number">12.1</span> Darwin's maize data<a class="anchor" aria-label="anchor" href="#darwins-maize-data"><i class="fas fa-link"></i></a>
</h2>
<p>Loss of genetic diversity is an important issue in the conservation of species. Declines in population size due to over exploitation, habitat fragmentation lead to loss of genetic diversity. Even populations restored to viable numbers through conservation efforts may suffer from continued loss of population fitness because of inbreeding depression.</p>
<p>Charles Darwin even wrote a book on the subject <em>"The Effects of Cross and Self-Fertilisation in the Vegetable Kingdom"</em>. In this he describes how he produced seeds of maize (<em>Zea mays</em>) that were fertilised with pollen from the same individual or from a different plant. The height of the seedlings that were produced from these were then measured as a proxy for their evolutionary fitness.</p>
<p>Darwin wanted to know whether inbreeding reduced the fitness of the selfed plants - this was his <strong>hypothesis</strong>. The data we are going to use today is from Darwin's original dataset.</p>
<a href="https://raw.githubusercontent.com/UEABIO/data-sci-v1/main/book/files/darwin.csv">
<button class="btn btn-success"><i class="fa fa-save"></i> Download Maize data as csv</button>
</a>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/">here</a></span><span class="op">)</span>

<span class="va">darwin</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"darwin.csv"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="warning">
<p>
Before you go any further - make sure your basic R project set up is up to scratch. Do you know where the data file is saved? Have you got separate subfolders set up within your project?
</p>
<p>
You should set up a script to put your work into - use this to write instructions and store comments. Use the File &gt; New Script menu item and select an R Script.
</p>
</div>
</div>
<div id="activity-1-carry-out-some-basic-exploratory-data-analysis" class="section level2" number="12.2">
<h2>
<span class="header-section-number">12.2</span> Activity 1: Carry out some basic exploratory data analysis<a class="anchor" aria-label="anchor" href="#activity-1-carry-out-some-basic-exploratory-data-analysis"><i class="fas fa-link"></i></a>
</h2>
<p>The first thing we should know by now is to always start by exploring our data. If you want to stretch yourself, see if you can perform a basic data check <strong>without</strong> prompts.</p>
<button id="displayTextunnamed-chunk-6" onclick="javascript:toggle('unnamed-chunk-6');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-6" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># check the structure of the data</span>
<span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">)</span>

<span class="co"># check data is in a tidy format</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">)</span>

<span class="co"># check variable names</span>
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">)</span>


<span class="co"># clean up column names</span>

<span class="va">darwin</span> <span class="op">&lt;-</span> <span class="fu">janitor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/janitor/man/clean_names.html">clean_names</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">)</span>

<span class="co"># check for duplication</span>
<span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span>

<span class="co"># check for typos - by looking at impossible values</span>
<span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>min<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">height</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>, 
            max<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">height</span>, na.rm<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>

<span class="co"># check for typos by looking at distinct characters/values</span>

<span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">pair</span><span class="op">)</span>

<span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span>

<span class="co"># missing values</span>
<span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span>

<span class="co"># quick summary</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">darwin</span><span class="op">)</span></code></pre></div>
</div>
</div>
</div>

<div id="visualisation" class="section level3" number="12.2.1">
<h3>
<span class="header-section-number">12.2.1</span> Visualisation<a class="anchor" aria-label="anchor" href="#visualisation"><i class="fas fa-link"></i></a>
</h3>
<p>Now seems like a good time for our first data visualisation.</p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">type</span>,
         y<span class="op">=</span><span class="va">height</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-Introduction-to-statistics_files/figure-html/unnamed-chunk-7-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># you could also substitute (or combine) other geoms including</span>
<span class="co"># geom_boxplot()</span>
<span class="co"># geom_violin()</span>
<span class="co"># geom_histogram()</span>
<span class="co"># Why not have a go and see what you can make?</span></code></pre></div>
<p>The graph clearly shows that the average height of the 'crossed' plants is greater than that of the 'selfed' plants. But we need to investigate further in order to determine whether the signal (any apparent differences in mean values) is greater than the level of noise (variance within the different groups).</p>
<p>The variance appears to be roughly similar between the two groups - though by making a graph we can now clearly see that in the crossed group, there is a <em>potential</em> outlier with a value of 12.</p>
</div>
<div id="comparing-groups" class="section level3" number="12.2.2">
<h3>
<span class="header-section-number">12.2.2</span> Comparing groups<a class="anchor" aria-label="anchor" href="#comparing-groups"><i class="fas fa-link"></i></a>
</h3>
<p>As we have seen previously we can use various tidy functions to determine the mean and standard deviations of our groups.</p>
<div class="sourceCode" id="cb285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span><span class="op">)</span>,
            sd<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">height</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
type
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Cross
</td>
<td style="text-align:right;">
20.19167
</td>
<td style="text-align:right;">
3.616945
</td>
</tr>
<tr>
<td style="text-align:left;">
Self
</td>
<td style="text-align:right;">
17.57500
</td>
<td style="text-align:right;">
2.051676
</td>
</tr>
</tbody>
</table></div>
</div>
<div class="info">
<p>
You should (re)familiarise yourself with how (and why) we calculate standard deviation.
</p>
</div>
<p>Summary statistics like these could be presented as figures or tables. We normally reserve tables for <strong>very</strong> simple sets of numbers, and this instance we could present both.</p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># make a new object</span>
<span class="va">darwin_summary</span> <span class="op">&lt;-</span><span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">type</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">height</span><span class="op">)</span>,
            sd<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">height</span><span class="op">)</span><span class="op">)</span>

<span class="co"># make a summary plot</span>
<span class="va">darwin_summary</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">type</span>,
             y<span class="op">=</span><span class="va">mean</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin<span class="op">=</span><span class="va">mean</span><span class="op">-</span><span class="va">sd</span>, ymax<span class="op">=</span><span class="va">mean</span><span class="op">+</span><span class="va">sd</span><span class="op">)</span><span class="op">)</span><span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-Introduction-to-statistics_files/figure-html/unnamed-chunk-10-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># put this at top of script</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span>

<span class="co"># use kable extra functions to make a nice table (could be replaced with kable() if needed)</span>
<span class="va">darwin_summary</span> <span class="op">%&gt;%</span> 
    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kbl.html">kbl</a></span><span class="op">(</span>caption<span class="op">=</span><span class="st">"Summary statistics of crossed and selfed maize plants"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, full_width <span class="op">=</span> <span class="cn">T</span>, position <span class="op">=</span> <span class="st">"left"</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-striped" style>
<caption>
<span id="tab:unnamed-chunk-10">Table 12.1: </span>Summary statistics of crossed and selfed maize plants
</caption>
<thead><tr>
<th style="text-align:left;">
type
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Cross
</td>
<td style="text-align:right;">
20.19167
</td>
<td style="text-align:right;">
3.616945
</td>
</tr>
<tr>
<td style="text-align:left;">
Self
</td>
<td style="text-align:right;">
17.57500
</td>
<td style="text-align:right;">
2.051676
</td>
</tr>
</tbody>
</table></div>
<p>Descriptive statistics and careful data checking are often skipped steps in the rush to answer the <strong>big</strong> questions. However, description is an essential part of early phase analysis.</p>
</div>
</div>
<div id="estimation" class="section level2" number="12.3">
<h2>
<span class="header-section-number">12.3</span> Estimation<a class="anchor" aria-label="anchor" href="#estimation"><i class="fas fa-link"></i></a>
</h2>
<p>In the section above we concentrated on description. But the hypothesis Darwin aimed to test was whether 'inbreeding reduced the fitness of the selfed plants'. To do this we will use the height of the plants as a proxy for fitness and explicitly address whether there is a <strong>difference</strong> in the mean heights of the plants between these two groups.</p>
<p>Our goal is to:</p>
<ul>
<li><p>Estimate the mean heights of the plants in these two groups</p></li>
<li><p>Estimate the mean <em>difference</em> in heights between these two groups</p></li>
<li><p>Quantify our <em>confidence</em> in these differences</p></li>
</ul>
<div id="differences-between-groups" class="section level3" number="12.3.1">
<h3>
<span class="header-section-number">12.3.1</span> Differences between groups<a class="anchor" aria-label="anchor" href="#differences-between-groups"><i class="fas fa-link"></i></a>
</h3>
<p>Darwin's data used match pairs - each pair shared one parent. So that in pair 1 the same parent plant was either 'selfed' or 'crossed' to produce offspring. This is a powerful approach to experimental design, as it means that we can look at the differences in heights across each of the 15 pairs of plants - rather than having to infer differences from two randomly derived groups.</p>
<p>In order to calculate the differences in height between each pair we need to do some data wrangling with <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">tidyr::pivot_wider()</a></code> <a href="#using-%60pivot%60-functions">Chapter 2</a> and calculations with <code>mutate</code>.</p>
</div>
</div>
<div id="activity-2-differences" class="section level2" number="12.4">
<h2>
<span class="header-section-number">12.4</span> Activity 2: Differences<a class="anchor" aria-label="anchor" href="#activity-2-differences"><i class="fas fa-link"></i></a>
</h2>
<p>Create a new column called difference with the height of the selfed plant in each pair subtracted from the crossed plant.</p>
<button id="displayTextunnamed-chunk-11" onclick="javascript:toggle('unnamed-chunk-11');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-11" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb288"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># pivot data to wide format then subtract Selfed plant heights from Crossed plant heights</span>

<span class="va">darwin_wide</span> <span class="op">&lt;-</span> <span class="va">darwin</span> <span class="op">%&gt;%</span> 
  <span class="fu">pivot_wider</span><span class="op">(</span>names_from <span class="op">=</span> <span class="va">type</span>, values_from <span class="op">=</span> <span class="va">height</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>difference <span class="op">=</span> <span class="va">Cross</span> <span class="op">-</span> <span class="va">Self</span><span class="op">)</span></code></pre></div>
</div>
</div>
</div>
<p>We now have the difference in height for each pair, we can use this to calculate the <strong>mean difference</strong> in heights between paired plants, and the amount of variance (as standard deviation)</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">difference_summary</span> <span class="op">&lt;-</span> <span class="va">darwin_wide</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">difference</span><span class="op">)</span>,
            sd<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">difference</span><span class="op">)</span>,
            n<span class="op">=</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>

<span class="va">difference_summary</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
n
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:right;">
2.616667
</td>
<td style="text-align:right;">
4.718047
</td>
<td style="text-align:right;">
15
</td>
</tr></tbody>
</table></div>
</div>
<div class="warning">
<p>
What we have just calculated is the average difference in height between these groups of plants and the standard deviation of the difference Moving forward we will be working a lot with estimating our confidence in differences between groups
</p>
</div>
<div id="standard-error-of-the-difference" class="section level3" number="12.4.1">
<h3>
<span class="header-section-number">12.4.1</span> Standard error of the difference<a class="anchor" aria-label="anchor" href="#standard-error-of-the-difference"><i class="fas fa-link"></i></a>
</h3>
<p>Remember standard deviation is a <em>descriptive</em> statistic - it measures the variance within our dataset - e.g. how closely do datapoints fit to the mean. However for <em>inferential</em> statistics we are more interested in our confidence in our estimation of the mean. This is where standard error comes in.</p>
<p>We can think of error as a standard deviation of the mean. The mean we have calculated is an estimate based on one sample of data. We would expect that if we sampled another 30 plants these would have a different sample mean. Standard error describes the variability we would expect among sample means if we repeated this experiment many times. So we can think of it as a measure of the confidence we have in our estimate of a <strong>true population mean</strong>.</p>
<p><span class="math display">\[
SE = \frac{s}{\sqrt(n)}
\]</span></p>
<p>As sample size increases the standard error should reduce - reflecting an increasing confidence in our estimate.</p>
<p>We can calculate the standard error for our sample by applying this equation to our <code>difference_summary</code> object, can you complete this?</p>
<button id="displayTextunnamed-chunk-14" onclick="javascript:toggle('unnamed-chunk-14');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-14" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">difference_summary</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>se<span class="op">=</span> <span class="va">sd</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
se
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:right;">
2.616667
</td>
<td style="text-align:right;">
4.718047
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
1.218195
</td>
</tr></tbody>
</table></div>
</div>
</div>
</div>
</div>
<p>Our estimate of the mean is not really very useful without an accompanying measuring of <em>uncertainty</em> like the standard error, in fact estimates of averages or differences should <strong>always</strong> be accompanied by their measure of uncertainty.</p>
</div>
<div id="activity-3-communicate" class="section level3" number="12.4.2">
<h3>
<span class="header-section-number">12.4.2</span> Activity 3: Communicate<a class="anchor" aria-label="anchor" href="#activity-3-communicate"><i class="fas fa-link"></i></a>
</h3>
<p>With the information above, how would you present a short sentence describing the average different in height?</p>
<button id="displayTextunnamed-chunk-15" onclick="javascript:toggle('unnamed-chunk-15');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-15" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<em>... the average difference in height was 2.62 ± 1.22 inches (mean ± SE).</em>
</div>
</div>
</div>
</div>
</div>
<div id="uncertainty" class="section level2" number="12.5">
<h2>
<span class="header-section-number">12.5</span> Uncertainty<a class="anchor" aria-label="anchor" href="#uncertainty"><i class="fas fa-link"></i></a>
</h2>
<p>With a mean and standard error of the difference in heights between inbred and crossed plants - how do we work out how much confidence we have in their being a difference between our <strong>population means</strong>?</p>
<p>Standard error is a measure of uncertainty, the larger the standard error the more <em>noise</em> around our data and the more uncertainty we have. The smaller the standard error the more confidence we can have that our difference in means is <em>real</em>.</p>
<ul>
<li><p>Null hypothesis - there is no difference in the mean height of self vs crossed plants</p></li>
<li><p>Alternate hypothesis - inbreeding reduces the fitness of the selfed plants, observed as selfed plants on average being smaller than crossed plants</p></li>
</ul>
<div class="info">
<p>
A statistical way of thinking about our inferences is in terms of confidence around keeping or rejecting the null hypothesis. The (alternate) hypothesis is simply one that contradicts the null.
</p>
<p>
When we decide whether we have enough confidence that a difference is real (e.g. we could reject the null hypothesis), we cannot ever be 100% certain that this isn't a false positive (also known as a Type I error). More on this later
</p>
</div>
<div id="normal-distribution-1" class="section level3" number="12.5.1">
<h3>
<span class="header-section-number">12.5.1</span> Normal distribution<a class="anchor" aria-label="anchor" href="#normal-distribution-1"><i class="fas fa-link"></i></a>
</h3>
<p>As we should remember, the normal distribution is the bell-shaped curve. It is defined by two parameters:</p>
<ul>
<li><p>the mean</p></li>
<li><p>the standard deviation</p></li>
</ul>
<p>The mean determines where the centre/peak of the bell curve is, the standard deviation determines the width of the bell (how long the tails are).</p>
<p>Large standard deviations produce wide bell curves, with short peaks. Small standard deviations produce narrow bell curves with tall peaks.</p>
<p>The bell curve occurs frequently in nature, most circumstances where we can think of a continuous measure coming from a population e.g. human mass, penguin flipper lengths or plant heights.</p>
<p>As a <em>probability</em> distribution, the area within the curve sums to the whole population (e.g. the probability that the curve contains every possible measurement is 1). Known proportions of the curve lie within certain distances from the centre e.g. 67.8% of observations should have values within one standard deviation of the mean. 95% of observations should have values within two standard deviations of the mean. This <em>idealized</em> normal distribution is presented below:</p>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#Create a sequence of 100 equally spaced numbers between -4 and 4</span>
<span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, length<span class="op">=</span><span class="fl">100</span><span class="op">)</span>

<span class="co">#create a vector of values that shows the height of the probability distribution</span>
<span class="co">#for each value in x</span>
<span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">dnorm</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>

<span class="co">#plot x and y as a scatterplot with connected lines (type = "l") and add</span>
<span class="co">#an x-axis with custom labels</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span><span class="op">(</span><span class="va">x</span>,<span class="va">y</span>, type <span class="op">=</span> <span class="st">"l"</span>, lwd <span class="op">=</span> <span class="fl">2</span>, axes <span class="op">=</span> <span class="cn">FALSE</span>, xlab <span class="op">=</span> <span class="st">""</span>, ylab <span class="op">=</span> <span class="st">""</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span><span class="op">(</span><span class="fl">1</span>, at <span class="op">=</span> <span class="op">-</span><span class="fl">3</span><span class="op">:</span><span class="fl">3</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"-3s"</span>, <span class="st">"-2s"</span>, <span class="st">"-1s"</span>, <span class="st">"mean"</span>, <span class="st">"1s"</span>, <span class="st">"2s"</span>, <span class="st">"3s"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="12-Introduction-to-statistics_files/figure-html/unnamed-chunk-17-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>How do we convert this information into how likely we are to observe a difference of 2.62 inches in plant heights if the 'true' difference between crosses and selfed plants is <em>zero</em>?</p>
<p>The <strong>central limit theorem</strong> states that if you have a population with mean and standard deviation, and take sufficiently large random samples from the population, then the distribution of the sample means will be approximately normally distributed. Standard error then is our measure of variability around our sample mean, and we will assume that we can apply a normal distribution to our ability to estimate the mean (<em>we will revisit this assumption later</em>).</p>
<p>So if we now center our bell curve on the estimate of the mean (2.62), then just over two thirds of the area under the curve is ± 1.22 inches. 95% of it will be within ± 2 standard errors, and 99.8% will be within ± 3 standard errors.</p>
<div class="inline-figure"><img src="12-Introduction-to-statistics_files/figure-html/unnamed-chunk-18-1.png" width="100%" style="display: block; margin: auto;"></div>
<p>Taking a look at this figure we can ask ourselves where is zero on our normal distribution? One way to think about this is, if the true difference between our plant groups is zero, how surprising is it that we estimated a difference between the groups of 2.62 inches?</p>
<p>If zero was close to the center of the bell curve, then our observed mean would not be surprising at all (<strong>if the null hypothesis is true</strong>). However in this case it is not in the middle of the bell. It falls in the left-hand tail, and it is &gt; than two standard deviations from our estimated mean.</p>
<p>We can describe this in two ways:</p>
<ul>
<li><p>We estimate that if we ran this experiment 100 times then &gt;95 of our experiments would estimate a mean difference between our plant groups that is &gt; 0.</p></li>
<li><p>This is also usually taken as the minimum threshold needed to <em>reject</em> a null hypothesis. We can think of the probability of estimating this mean difference, if our true mean difference was zero, as p &lt; 0.05.</p></li>
</ul>
<p>You will probably be very used to a threshold for null hypothesis rejection of <span class="math inline">\(\alpha\)</span> = 0.05, but this only the very lowest level of confidence at which we can pass a statistical test. If we increase the severity of our test so that the minimum we require is <span class="math inline">\(\alpha\)</span> = 0.001 or 99% confidence, we can see that we no longer believe we have enough confidence to reject the null hypothesis (0 is within 3 s.d. of our estimated mean).</p>
</div>
<div id="confidence-intervals" class="section level3" number="12.5.2">
<h3>
<span class="header-section-number">12.5.2</span> Confidence Intervals<a class="anchor" aria-label="anchor" href="#confidence-intervals"><i class="fas fa-link"></i></a>
</h3>
<p>Because ± 2 standard errors covers the central 95% of the area under the normal curve, we refer to this as our 95% confidence interval. We can calculate confidence intervals for any level, but commonly we refer to standard error (68% CI), 95% and 99%.</p>
<p>We can work out the 95% confidence interval range of our estimated mean as follows:</p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lowerCI</span> <span class="op">&lt;-</span> <span class="fl">2.62</span><span class="op">-</span><span class="op">(</span><span class="fl">2</span><span class="op">*</span><span class="fl">1.22</span><span class="op">)</span>

<span class="va">upperCI</span> <span class="op">&lt;-</span> <span class="fl">2.62</span><span class="op">+</span><span class="op">(</span><span class="fl">2</span><span class="op">*</span><span class="fl">1.22</span><span class="op">)</span>

<span class="va">lowerCI</span>
<span class="va">upperCI</span></code></pre></div>
<pre><code>## [1] 0.18
## [1] 5.06</code></pre>
<p>A common mistake it to state that we are 95% confident that the 'true' mean lies within our interval. But <em>technically</em> it refers to the fact that if we kept running this experiment again and again the intervals we calculate would capture the true mean in 95% of experiments. So really we are saying that we are confident we would capture the true mean in 95% of our experiments.</p>
<p>How might we write this up?</p>
<div class="info">
<p>
The maize plants that have been cross pollinated were taller on average than the self-pollinated plants, with a mean difference in height of 2.62 [0.18, 5.06] inches (mean [95% CI]).
</p>
</div>
<blockquote>
<p>Note that because it is possible to generate multiple types of average and confidence interval, we clearly state them in our write up. The same would be true if you were presenting the standard error (± S.E.) or the standard deviation (± S.D.) or a median and interquartile range (median [± IQR]).</p>
</blockquote>
<p>The above is a good example of a simple but clear write-up because it clearly describes the <em>direction</em> of the difference, the <em>amount</em> and the <em>error</em> in our estimate.</p>
</div>
</div>
<div id="summary-1" class="section level2" number="12.6">
<h2>
<span class="header-section-number">12.6</span> Summary<a class="anchor" aria-label="anchor" href="#summary-1"><i class="fas fa-link"></i></a>
</h2>
<p>Statistics is all about trying to interpret whether the signal (of a difference or trend) is stronger than the amount of noise (variability). In a sample the standard deviation is a strong choice for estimating this <em>within</em> a dataset. The standard deviation of the sampling distribution of the mean is known as the standard error. The standard error (of the mean) is a measure of the precision we have in our estimate of the mean. Thanks to the central limit theorem and normal distribution we can use the variability in our estimate to calculate confidence intervals, and decide whether our signal of an effect is strong enough to reject a null hypothesis (of no effect or no difference).</p>
<p>Next time we will start working with linear models - this approach allows us to estimate means and intervals in a more sophisticated (and automated) way.</p>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    license
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="data-insights-part-two.html"><span class="header-section-number">11</span> Data insights part two</a></div>
<div class="next"><a href="introduction-to-linear-models.html"><span class="header-section-number">13</span> Introduction to Linear Models</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#introduction-to-statistics"><span class="header-section-number">12</span> Introduction to statistics</a></li>
<li><a class="nav-link" href="#darwins-maize-data"><span class="header-section-number">12.1</span> Darwin's maize data</a></li>
<li>
<a class="nav-link" href="#activity-1-carry-out-some-basic-exploratory-data-analysis"><span class="header-section-number">12.2</span> Activity 1: Carry out some basic exploratory data analysis</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#visualisation"><span class="header-section-number">12.2.1</span> Visualisation</a></li>
<li><a class="nav-link" href="#comparing-groups"><span class="header-section-number">12.2.2</span> Comparing groups</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#estimation"><span class="header-section-number">12.3</span> Estimation</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#differences-between-groups"><span class="header-section-number">12.3.1</span> Differences between groups</a></li></ul>
</li>
<li>
<a class="nav-link" href="#activity-2-differences"><span class="header-section-number">12.4</span> Activity 2: Differences</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#standard-error-of-the-difference"><span class="header-section-number">12.4.1</span> Standard error of the difference</a></li>
<li><a class="nav-link" href="#activity-3-communicate"><span class="header-section-number">12.4.2</span> Activity 3: Communicate</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#uncertainty"><span class="header-section-number">12.5</span> Uncertainty</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#normal-distribution-1"><span class="header-section-number">12.5.1</span> Normal distribution</a></li>
<li><a class="nav-link" href="#confidence-intervals"><span class="header-section-number">12.5.2</span> Confidence Intervals</a></li>
</ul>
</li>
<li><a class="nav-link" href="#summary-1"><span class="header-section-number">12.6</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/UEABIO/data-sci-v1/blob/main/book/12-Introduction-to-statistics.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/UEABIO/data-sci-v1/edit/main/book/12-Introduction-to-statistics.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>5023Y</strong>: Data Science for Biologists" was written by Philip T. Leftwich. It was last built on 2022-12-11.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
